[package]
name = "bacchus-sign"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "0.13.0"
libsystemd = "0.3.1"
log = "0.4.14"
syslog = "5.0.0"
thiserror = "1.0.26"
tweetnacl = "0.4.0"

[dependencies.tokio]
version = "1.11.0"
features = ["rt-multi-thread", "fs", "io-util", "net", "signal", "macros"]
