name: Lint and build
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true
    - name: Install cargo-deb
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-deb
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D clippy::all
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all
    - name: Run cargo deb
      uses: actions-rs/cargo@v1
      with:
        command: deb
        args: --no-build
    - name: Upload build artifact (bins)
      uses: actions/upload-artifact@v2
      with:
        name: bins
        path: |
          target/release/bacchus-sign
          target/release/bacchus-sign-keys
    - name: Upload build artifact (deb)
      uses: actions/upload-artifact@v2
      with:
        name: deb
        path: |
          target/debian/*.deb
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/release/bacchus-sign
          target/release/bacchus-sign-keys
          target/debian/*.deb
